### ISSUE TITLE
I don't know

### ISSUE THREAD

**Issue by patryk110200** [NexiusTailer/Nex-AC#122]
C:\pawno\include\nex_ac.inc(2035) : warning 219: local variable "X" shadows a variable at a preceding level
C:\pawno\include\nex_ac.inc(2035) : warning 219: local variable "Y" shadows a variable at a preceding level
C:\pawno\include\nex_ac.inc(2035) : warning 219: local variable "Z" shadows a variable at a preceding level
C:\pawno\include\nex_ac.inc(2056) : warning 219: local variable "X" shadows a variable at a preceding level
C:\pawno\include\nex_ac.inc(2056) : warning 219: local variable "Y" shadows a variable at a preceding level
C:\pawno\include\nex_ac.inc(2056) : warning 219: local variable "Z" shadows a variable at a preceding level
C:\pawno\include\nex_ac.inc(2584) : warning 219: local variable "X" shadows a variable at a preceding level
C:\pawno\include\nex_ac.inc(2584) : warning 219: local variable "Y" shadows a variable at a preceding level
C:\pawno\include\nex_ac.inc(2584) : warning 219: local variable "Z" shadows a variable at a preceding level
C:\pawno\include\nex_ac.inc(2584) : warning 219: local variable "X" shadows a variable at a preceding level
C:\pawno\include\nex_ac.inc(2584 -- 2586) : warning 219: local variable "Y" shadows a variable at a preceding level
C:\pawno\include\nex_ac.inc(2584 -- 2586) : warning 219: local variable "Z" shadows a variable at a preceding level
C:\pawno\include\nex_ac.inc(2656) : warning 219: local variable "X" shadows a variable at a preceding level
C:\pawno\include\nex_ac.inc(2656) : warning 219: local variable "Y" shadows a variable at a preceding level
C:\pawno\include\nex_ac.inc(2656) : warning 219: local variable "Z" shadows a variable at a preceding level
C:\pawno\include\nex_ac.inc(2656) : warning 219: local variable "X" shadows a variable at a preceding level
C:\pawno\include\nex_ac.inc(2656 -- 2658) : warning 219: local variable "Y" shadows a variable at a preceding level
C:\pawno\include\nex_ac.inc(2656 -- 2658) : warning 219: local variable "Z" shadows a variable at a preceding level
C:\pawno\include\nex_ac.inc(2674) : warning 219: local variable "X" shadows a variable at a preceding level
C:\pawno\include\nex_ac.inc(2674) : warning 219: local variable "Y" shadows a variable at a preceding level
C:\pawno\include\nex_ac.inc(2674) : warning 219: local variable "Z" shadows a variable at a preceding level
C:\pawno\include\nex_ac.inc(2674) : warning 219: local variable "X" shadows a variable at a preceding level
C:\pawno\include\nex_ac.inc(2674 -- 2676) : warning 219: local variable "Y" shadows a variable at a preceding level
C:\pawno\include\nex_ac.inc(2674 -- 2676) : warning 219: local variable "Z" shadows a variable at a preceding level
C:\pawno\include\nex_ac.inc(7013) : warning 201: redefinition of constant/macro (symbol "OnVehicleSpawn")
Pawn compiler 3.2.3664	 	 	Copyright (c) 1997-2006, ITB CompuPhase

25 Warnings.
[Finished in 23.5s]

**Comment by NexiusTailer** [comment]
Find in your script X, Y and Z variables and rename them to any other name. And don't name global variables such commonly used names, this is a bad practice.

**Comment by patryk110200** [comment]
Yes, I know, only that I use X, Y, Z for "public", so it should not be mixed up (I don't use Float: X etc. in "new")

**Comment by patryk110200** [comment]
C:\pawno\include\nex-ac.inc(2035) : warning 219: local variable "X" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(2035) : warning 219: local variable "Y" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(2035) : warning 219: local variable "Z" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(2056) : warning 219: local variable "X" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(2056) : warning 219: local variable "Y" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(2056) : warning 219: local variable "Z" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(2584) : warning 219: local variable "X" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(2584) : warning 219: local variable "Y" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(2584) : warning 219: local variable "Z" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(2584) : warning 219: local variable "X" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(2584 -- 2586) : warning 219: local variable "Y" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(2584 -- 2586) : warning 219: local variable "Z" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(2656) : warning 219: local variable "X" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(2656) : warning 219: local variable "Y" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(2656) : warning 219: local variable "Z" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(2656) : warning 219: local variable "X" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(2656 -- 2658) : warning 219: local variable "Y" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(2656 -- 2658) : warning 219: local variable "Z" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(2674) : warning 219: local variable "X" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(2674) : warning 219: local variable "Y" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(2674) : warning 219: local variable "Z" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(2674) : warning 219: local variable "X" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(2674 -- 2676) : warning 219: local variable "Y" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(2674 -- 2676) : warning 219: local variable "Z" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(7013) : warning 201: redefinition of constant/macro (symbol "OnVehicleSpawn")
Pawn compiler 3.2.3664	 	 	Copyright (c) 1997-2006, ITB CompuPhase


1 Error.
[Finished in 11.9s]



I take this error IN CLEAR GAMEMODE without custom new's,public's,stock's etc.
